### ISSUE TITLE
how to train source model on custom dataset？

### ISSUE THREAD

**Issue by ZFU123456** [junia3/LPLD#3]
can you show how to train source model on custom dataset？

**Comment by junia3** [comment]
You need to add custom dataset/loader and evaluator in detectron2.

**Comment by ZFU123456** [comment]
> You need to add custom dataset/loader and evaluator in detectron2.

When I use Faster R-CNN to train on Cityscapes data,  but when I test the model, the Average Precision (AP) is always 0. Can you provide the code for the first stage of training on the source domain?

**Comment by junia3** [comment]
Please refer to [detectron2](https://github.com/facebookresearch/detectron2) official code.
