### ISSUE TITLE
why

### ISSUE THREAD

**Issue by ZFU123456** [junia3/LPLD#5]

**Comment by ZFU123456** [comment]
First, I downloaded the baseline model you provided: kitti_baseline. Then, I continued training using the command:
CUDA_VISIBLE_DEVICES=0 python tools/train_main.py --config-file configs/sfda/sfda_kitti2city.yaml --model-dir ./source_model//kitti2city/model_final.pth
However, the results I obtained were:
![1721877264178](https://github.com/user-attachments/assets/a472b363-ba8f-4d7e-bdfa-c0ffbc368a6e)
This indicates that the model's performance metrics (Average Precision at different IoU thresholds) are relatively low, with AP at 12.5599%, AP50 at 25.0634%, and AP75 at 10.7514%.
Did I make a mistake somewhere? Please give me some suggestions.

**Comment by junia3** [comment]
Double the value because it includes the background class.

**Comment by ZFU123456** [comment]
> Double the value because it includes the background class.
AP： 12.5599  doubleed --》25.1198，but the paper's AP  is 
![1721879328718](https://github.com/user-attachments/assets/9a1bb66e-4717-48af-89e9-a58c4ca333dc)
, The gap is significant.

**Comment by junia3** [comment]
Benchmark is AP50

**Comment by ZFU123456** [comment]
> Benchmark is AP50 please refer to paper implementation detail.
thanks, now I have two questions:
1.  I downloaded the baseline model you provided: cityspace_baseline. Then, I continued training, the result is :
![image](https://github.com/user-attachments/assets/d84509bb-901d-4d19-9613-9113ff75be6c)
the paper's AP is 40.4. The gap is significant.
2. I trained cityspaces dataset with fasterrcnn in detectron2, the .yaml is:
![1721896466216](https://github.com/user-attachments/assets/c50b78ae-0261-4d61-bc98-92f2db06b810)
Then,  I continued training, the result is:
![image](https://github.com/user-attachments/assets/33777989-4e60-4c9b-a762-962748f56edc)
The difference between the result and this in the paper is quite significant.
I would be very grateful if you could give me some advice.

**Comment by junia3** [comment]
1. I think this issue occurs because the current code does not fully align with our original code, and we are continuously refactoring it for the final version. We will finalize the random seed and proper experimental settings. So please wait for the later update version of our code.

3. Please refer to the IRG (CVPR) and PETS (ICCV) papers and their respective source codes. These topics are beyond the scope of our work.
